#! /usr/bin/python

import os

def get_mt_dir():
	return os.path.dirname(os.path.realpath(__file__))

def get_project_dir():
	return os.getcwd()

if __name__ == "__main__":
	print "mt_dir: %s"%get_mt_dir()
	print "cwd: %s"%get_project_dir()
	cmd = "make -C %s/src RENDU_PATH=%s"%(get_mt_dir(), get_project_dir())
	os.system(cmd)