#!/usr/bin/python

try:
	import ConfigParser
except:
	import configparser as ConfigParser
import os

def get_mt_dir():
	return os.path.dirname(os.path.realpath(__file__))

def get_project_dir():
	return os.getcwd()

if __name__ == "__main__":
	config = ConfigParser.ConfigParser()
	config.readfp(open("%s/.moulitest.cfg"%get_project_dir()))
	headers_dir = config.get('general', 'headers')
	sources = config.get('general', 'sources')

	cmd = "make -C '{mt_dir}/../src' MT_RENDU_PATH='{project_dir}' MT_HEADERS='{headers_dir}' MT_SOURCES='{sources}'".format(
		mt_dir= get_mt_dir(),
		project_dir = get_project_dir(),
		headers_dir = headers_dir,
		sources = sources,
	)
	os.system(cmd)
